add test on unexepcted execution

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -143,7 +143,7 @@ jobs:
         run: |
           docker  run --pull never --name t1 -v ${PWD}/tests/projects/sample1/:/jmeter/project -e JMETER_PLUGINS_MANAGER_INSTALL_LIST="jpgc-dbmon=0.1" -e JMETER_PLUGINS_MANAGER_INSTALL_FOR_JMX="true"  -e JMETER_JMX="test-plan.jmx" ${{ steps.result.outputs.currentImage }} hello
           expected='hello'
-          if [[ $(docker logs t1 | grep $expected ) ]];then echo "$expected found"; else "echo $expected not found"; exit 1; fi;
+          if [[ $(docker logs t1 | grep $expected ) ]];then echo "$expected found"; else echo "$expected not found"; exit 1; fi;
           docker commit t1 t1 
           container-structure-test test -v info --image t1 --config tests/container-structure-test/sample1-install-plugins.yaml
           container-structure-test test -v info --image t1 --config tests/container-structure-test/install-plugins-by-manager.yaml
@@ -155,10 +155,10 @@ jobs:
         if: ${{ matrix.with-plugins == 'true' }}
         run: |
           docker  run --pull never --name t1 -v ${PWD}/tests/projects/sample1/:/jmeter/project -e JMETER_CHECK_ONLY=true -e JMETER_PLUGINS_MANAGER_INSTALL_LIST="jpgc-dbmon=0.1" -e JMETER_PLUGINS_MANAGER_INSTALL_FOR_JMX="true"  -e JMETER_JMX="test-plan.jmx" ${{ steps.result.outputs.currentImage }} hello
-          expected='hello'
-          if [[ $(docker logs t1 | grep $expected ) ]];then echo "$expected found"; else "echo $expected not found"; exit 1; fi;
+          unexpected='hello'
+          if [[ $(docker logs t1 | grep $unexpected ) ]];then echo "unexpected $unexpected found";exit 1; else echo "unexpected $unexpected not found";  fi;
           expected='TestPlanCheckTool: JMX is fine'
-          if [[ $(docker logs t1 | grep $expected ) ]];then echo "$expected found"; else "echo $expected not found"; exit 1; fi;
+          if [[ $(docker logs t1 | grep $expected ) ]];then echo "$expected found"; else echo "$expected not found"; exit 1; fi;
           docker commit t1 t1 
           container-structure-test test -v info --image t1 --config tests/container-structure-test/sample1-install-plugins.yaml
           container-structure-test test -v info --image t1 --config tests/container-structure-test/install-plugins-by-manager.yaml
