add assetion log

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -87,7 +87,6 @@ jobs:
         run: |
           container-structure-test test --image ${{ steps.prep.outputs.image }}:${{ matrix.jmeter-branch }} --config tests/container-structure-test/jmeter-install.yaml
 
-
       - name: Test Jmeter base Plugin Install
         run: |
           container-structure-test test --image ${{ steps.prep.outputs.image }}:${{ matrix.jmeter-branch }} --config tests/container-structure-test/plugins-base-install.yaml
@@ -95,6 +94,8 @@ jobs:
       - name: Test Jmeter Project Plugin Install
         run: |
           docker  run --name t1 -v ${PWD}/tests/sample1/:/jmeter/project ${{ steps.prep.outputs.image }}:${{ matrix.jmeter-branch }} hello
+          expected='helloo'
+          if [[ $(docker logs t1 | grep '$expected' ) ]];then echo "$expected found"; else "echo $expected not found"; exit 1; fi;
           docker commit t1 t1 
           container-structure-test test --image t1 --config tests/container-structure-test/sample1-install-plugins.yaml
           docker rmi t1
