correct test

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -95,7 +95,7 @@ jobs:
         run: |
           docker  run --name t1 -v ${PWD}/tests/sample1/:/jmeter/project ${{ steps.prep.outputs.image }}:${{ matrix.jmeter-branch }} hello
           expected='hello'
-          if [[ $(docker logs t1 | grep '$expected' ) ]];then echo "$expected found"; else "echo $expected not found"; exit 1; fi;
+          if [[ $(docker logs t1 | grep $expected ) ]];then echo "$expected found"; else "echo $expected not found"; exit 1; fi;
           docker commit t1 t1 
           container-structure-test test --image t1 --config tests/container-structure-test/sample1-install-plugins.yaml
           docker rmi t1
